import SwiftUI

struct AppScopeToggleScreen: View {
    @EnvironmentObject var container: CodexiaContainer
    
    var body: some View {
        VStack(spacing: 20) {
            Text("Momma Mobile: AppScopeToggle").font(.title).bold()
            Text("Action")
            Text("Error: Not logged in")
            Text("Waiting for Child ID...")
            Text("Child ID received: $childId. Creating Firebase listener...")
            Text("guardianLinks/$guardianId/appScope/$childId/enabled")
            Text("Error: Guardian ID is null.")
            Text("guardianLinks/$guardianId/appScope/$childId/blockedApps")
            Text("Attaching Firebase listener...")
            Text("Success! Firebase value received: $isEnabled")
            Text("Firebase Listener Error: ${error.message}")
            Text("AppScopeToggle")
            Text("Action")
            Text("AppScope™ Filter")
            ProgressView()
            Text("Loading from Firebase...")
            Toggle("Action", isOn: .constant(true))
            Text("AppScope Status")
            Text("Action")
            Text("Active - Blocking ${blockedApps.size} apps")
            Toggle("Action", isOn: .constant(true))
            Text("Blocked Apps")
            Text("Add app")
            Text("Action")
            Text("No blocked apps yet. Tap + to add apps to block.")
            Text("Action")
            Text("Action")
            Text("Remove")
            Text("Block App")
            Text("Action")
            Text("Enter the package name of the app to block")
            Text("Action")
            Text("Examples: com.squareup.cash (Cash App), com.snapchat.android (Snapchat), com.zhiliaoapp.musically (TikTok)")
            TextField("Action", text: .constant(""))
                .textFieldStyle(.roundedBorder)
            Text("Package name")
            Text("com.example.app")
            Text("Add")
            Text("Cancel")
            Spacer()
        }.padding()
        .navigationTitle("AppScopeToggle")
    }
}