import SwiftUI

struct ChildLinkActivityScreen: View {
    @EnvironmentObject var container: CodexiaContainer
    
    var body: some View {
        VStack(spacing: 20) {
            Text("Momma Mobile: ChildLinkActivity").font(.title).bold()
            Text("Action")
            Text("ChildLinkActivity")
            Text("token")
            Text("Processing QR code link...")
            Text("Invalid link - no token found")
            Text("token=")
            Text("Invalid QR code format")
            Text("nettielink://")
            Text("nettielink://")
            Text("Scan failed: ${it.localizedMessage}")
            Text("Camera error: ${e.localizedMessage}")
            Text("token=")
            Text("&")
            Text("ChildLinkActivity")
            Text("No child ID found. Please log in.")
            Text("ChildLinkActivity")
            Text("linkingTokens/$token")
            Text("Invalid or expired QR code")
            Text("guardianId")
            Text("expiresAt")
            Text("used")
            Text("Invalid QR code data")
            Text("This QR code has already been used")
            Text("QR code has expired. Please generate a new one.")
            Text("used")
            Text("Child Device")
            Text("yyyy-MM-dd HH:mm:ss")
            Text("nickname")
            Text("last_seen")
            Text("mood")
            Text("linked_at")
            Text("guardianLinks/$guardianId/linkedChildren/$childId")
            Text("nettie_prefs")
            Text("household_id")
            Text("device_nickname")
            Text("ChildLinkActivity")
            Text("ChildLinkActivity")
            Text("Successfully linked to guardian! 🎯")
            Text("ChildLinkActivity")
            Text("Link failed: ${e.localizedMessage}")
            Text("ChildLinkActivity")
            Text("Failed to validate QR code: ${e.localizedMessage}")
            Text("ChildLinkActivity")
            Text("No child ID found. Please log in.")
            Text("guardianLinks/$householdId/linkedChildren/$childId")
            Text("Child Device")
            Text("yyyy-MM-dd HH:mm:ss")
            Text("calm")
            Text("nickname")
            Text("last_seen")
            Text("mood")
            Text("nettie_prefs")
            Text("household_id")
            Text("device_nickname")
            Text("ChildLinkActivity")
            Text("ChildLinkActivity")
            Text("Linked to household: $householdId")
            Text("Link failed: ${it.localizedMessage}")
            Text("🔒 Enable Device Protection?")
            Text("To prevent unauthorized app removal, Momma Mobile needs Device Administrator permission. This ensures the app stays protected and can't be uninstalled without guardian authorization.")
            Text("Enable Protection")
            Text("Skip")
            Text("⚠️ Warning: App can be uninstalled without protection")
            Text("📊 Enable Uninstall Detection?")
            Text("Momma Mobile can detect when someone tries to uninstall the app and alert your guardian immediately. This requires Usage Access permission.")
            Text("Enable Detection")
            Text("Skip")
            Text("⚠️ Uninstall attempts won't be detected")
            Text("Please enable Usage Access for Momma Mobile")
            Text("ChildLinkActivity")
            Text("✅ Device protection already enabled")
            Text("Momma Mobile needs Device Admin permission to prevent unauthorized app removal. ")
            Text("This ensures your guardian can keep you safe even if someone tries to uninstall the app.")
            Text("✅ Device protection enabled!")
            Text("ChildLinkActivity")
            Text("⚠️ Device protection not enabled - app may be vulnerable to removal")
            Text("ChildLinkActivity")
            Text("Enable Stealth Mode?")
            Text("Momma Mobile can quietly protect you in the background. Would you like to hide the app icon from your home screen?")
            Text("Yes, hide it")
            Text("Stealth Mode enabled. App icon hidden.")
            Text("Failed to enable Stealth Mode: ${e.localizedMessage}")
            Text("No, keep visible")
            Text("Enable Emotional Radar?")
            Text("To help protect you from harmful messages, Nettie needs permission to become your default SMS app. This allows her to scan incoming texts for emotional safety risks. No messages are stored or shared — only flagged patterns are reported to your guardian.")
            Text("Enable Emotional Radar")
            Text("Not now")
            Text("Emotional radar not enabled. You can turn it on later in settings.")
            Text("SMS role not available on this device.")
            Spacer()
        }.padding()
        .navigationTitle("ChildLinkActivity")
    }
}