import SwiftUI

struct CompatibilityVectorScreen: View {
    @StateObject private var viewModel = CompatibilityVectorViewModel()

    var body: some View {
        NavigationView {
            Text("Timestamp")
            Text("DocumentId")
            Text("ServerTimestamp")
            Text("Represents")
            Text("This")
            Text("CompatibilityVector")
            Text("DocumentId")
            Text("String")
            Text("String")
            Text("Values")
            Text("ValuesVector")
            Text("Conflict")
            Text("ConflictVector")
            Text("Future")
            Text("FutureVector")
            Text("Communication")
            Text("CommunicationVector")
            Text("Philosophy")
            Text("PhilosophyVector")
            Text("Metadata")
            Text("Double")
            Text("Double")
            Text("List")
            Text("ServerTimestamp")
            Text("Timestamp")
            Text("ServerTimestamp")
            Text("Timestamp")
            Text("Values")
            Text("ValuesVector")
            Text("Double")
            Text("Double")
            Text("Double")
            Text("Double")
            Text("Double")
            Text("Double")
            Text("Conflict")
            Text("ConflictVector")
            Text("ConflictStyle")
            Text("Double")
            Text("Double")
            Text("Double")
            Text("Double")
            Text("Double")
            VStack {
            }
            Text("AVOIDER")
            Text("ACCOMMODATOR")
            Text("COMPETITOR")
            Text("COLLABORATOR")
            Text("BALANCED")
            Text("Future")
            Text("FutureVector")
            Text("ChildrenDesire")
            Text("Double")
            Text("Double")
            Text("Double")
            Text("Double")
            Text("Double")
            VStack {
            }
            Text("UNSURE")
            Text("Communication")
            Text("CommunicationVector")
            Text("Double")
            Text("Double")
            Text("Double")
            Text("Double")
            Text("Double")
            Text("Double")
            Text("Philosophy")
            Text("PhilosophyVector")
            Text("Double")
            Text("Double")
            Text("Double")
            Text("Double")
            Text("Double")
            Text("Double")
                .navigationTitle("CompatibilityVector")
        }
        .onAppear { viewModel.onEvent(CompatibilityVectorEvent.onAppear) }
    }
}
