import SwiftUI

struct ConsentModalScreen: View {
    @EnvironmentObject var container: CodexiaContainer
    
    var body: some View {
        VStack(spacing: 20) {
            Text("Momma Mobile: ConsentModal").font(.title).bold()
            Text("ConsentModal")
            Text("Action")
            Text("discord")
            Text("roblox")
            Text("facebook")
            Text("features/sms")
            Text("\\n\\nThis applies to all interactions on this platform, including private messages.")
            Text("Consent for $platform")
            Text("I Consent")
            Text("Cancel")
            Text("Revoke Consent for $platform")
            Text("Are you sure you want to revoke consent? Nettie will no longer monitor this platform.")
            Text("Revoke")
            Text("Cancel")
            Text("nettie_prefs")
            Text("guardian_id")
            Text("household_id")
            Text("⚠️ Missing guardian ID. Consent not logged.")
            Text("Consent could not be logged. Missing guardian info.")
            Text("initial")
            Text("consent_logs/$householdId/$guardianId")
            Text("timestamp")
            Text("consentGiven")
            Text("ipAddress")
            Text("version")
            Text("userAgent")
            Text("consentType")
            Text("platform")
            Text("✅ Consent logged for $platform: granted=$granted")
            Text("❌ Failed to log consent: ${it.localizedMessage}")
            Text("consent_status/$householdId/$guardianId")
            Text("consentGiven")
            Text("lastUpdated")
            Text("version")
            Text("platform")
            Text("✅ Consent status updated for $platform")
            Text("❌ Failed to update consent status: ${it.localizedMessage}")
            Text("local")
            Text("mobile-device")
            Text("MommaNettie-Android/${android.os.Build.VERSION.RELEASE} (${android.os.Build.MODEL})")
            Spacer()
        }.padding()
        .navigationTitle("ConsentModal")
    }
}