import SwiftUI

struct EmotionalScannerScreen: View {
    @EnvironmentObject var container: CodexiaContainer
    
    var body: some View {
        VStack(spacing: 20) {
            Text("Momma Mobile: EmotionalScanner").font(.title).bold()
            Text("EmotionalScanner")
            Text("get back at you")
            Text("get back to you")
            Text("got back to")
            Text("getting back to")
            Text("hit me back")
            Text("text me back")
            Text("call me back")
            Text("write back")
            Text("talk back")
            Text("come back")
            Text("be back")
            Text("right back")
            Text("back at")
            Text("back to")
            Text("lol")
            Text("lmao")
            Text("haha")
            Text("omg")
            Text("wtf")
            Text("brb")
            Text("ttyl")
            Text("idk")
            Text("tbh")
            Text("ngl")
            Text("phrase")
            Text("sms")
            Text("unknown")
            Text("🟢 Message contains whitelisted casual phrase, skipping critical flags")
            Text("Action")
            Text("Action")
            Text("⚪ Skipping whitelisted phrase: '$phrase'")
            Text("\\\\b${Regex.escape(phraseLower)}\\\\b")
            Text("⚪ Skipping partial match for CRITICAL phrase: '$phrase'")
            Text("phrase")
            Text("Action")
            Text("Action")
            Text("⚪ Skipping single emoji in long message: '$emoji'")
            Text("emoji")
            Text("🟢 Message scanned from $sourceApp: no threats detected.")
            Text("🚨 Message from $sourceApp flagged with ${uniqueResults.size} unique issues.")
            Text("🔥")
            Text("$logIcon ${detection.source.uppercase()}: '${detection.match}' | Category: ${detection.meta.category}, Severity: ${detection.meta.severity}")
            Spacer()
        }.padding()
        .navigationTitle("EmotionalScanner")
    }
}