import SwiftUI

struct FinalSelectionScreen: View {
    @StateObject private var viewModel = FinalSelectionViewModel()

    var body: some View {
        NavigationView {
            ProgressView()
            Spacer()
            Text("")
            Spacer()
            Spacer()
            Text("")
            Spacer()
            Spacer()
            Text("")
            Spacer()
            Text("")
            Spacer()
            Spacer()
            Text("")
            Spacer()
            Spacer()
            Spacer()
            Spacer()
            Button(action: { }) {
                Text(" ")
            }
            Text("")
            Spacer()
            Text("")
            Spacer()
            Text("")
            Spacer()
            Text("")
            Spacer()
            Text("")
            Spacer()
            Spacer()
            Spacer()
            Spacer()
            Spacer()
            Button(action: { }) {
                Text(" ")
            }
            Text("Continue")
            Spacer()
            Spacer()
            Text("")
            Spacer()
            Text("")
            Spacer()
            Text("")
            Spacer()
            Text("")
            Text("")
            Spacer()
            Text("")
            Spacer()
            Spacer()
            Spacer()
            Spacer()
            Text("")
            Spacer()
            Spacer()
            Spacer()
            Spacer()
            Text("")
            Spacer()
            Spacer()
            Text("")
            Text("")
            Spacer()
            Text("")
            Text("")
            Text("")
            Spacer()
            Text("")
            Spacer()
            Text("")
            Text("")
            Spacer()
            Text("")
            Spacer()
            Button(action: { }) {
                Text(" ")
            }
            Text("Try Again")
            Spacer()
            Text("Go Back").navigationTitle("FinalSelection")
        }.onAppear { viewModel.onEvent(FinalSelectionEvent.onAppear) }
    }
}
