import SwiftUI

struct FreezeReflexFragmentScreen: View {
    @StateObject private var viewModel = FreezeReflexFragmentViewModel()

    var body: some View {
        NavigationStack {
            Text("Blocked (${blockedContacts.size})")
            Text("Conversations")
            Text("Attempts (${blockedAttempts.size})")
            Text("Settings")
            ProgressView()
            Text("")
            Text("Block Contact Manually")
            Text("")
            Text("Phone Number or Contact ID")
            Text("e.g., +1234567890")
            Spacer()
            Text("Platform")
            Text("")
            Spacer()
            Text("Reason (Optional)")
            Text("e.g., Known predator, suspicious behavior")
            Button(action: { }) {
                Text(" ")
            }
            Text("Block Contact")
            Text("Cancel")
            Text("")
            Spacer()
            Text("")
            Text("")
            Text("✅")
            Spacer()
            Text("")
            Text("")
            Spacer()
            Text("")
            Text("")
            Text("")
            Spacer()
            Text("")
            Text("")
            Spacer()
            Text("View Message")
            Button(action: { }) {
                Text(" ")
            }
            Text("Unblock")
            Text("Original Message")
            Text("")
            Spacer()
            Text("")
            Text("Close")
            Text("No conversation logs yet")
            Spacer()
            Text("")
            Text("")
            Spacer()
            Text("")
            Spacer()
            Text("")
            Text("")
            Text("")
            Spacer()
            Text("")
            Text("🛡️")
            Spacer()
            Text("No Blocked Attempts")
            Text("Blocked contacts haven't tried to message yet.")
            Spacer()
            Text("")
            Text("")
            Text("")
            Spacer()
            Text("")
            Spacer()
            Text("")
            Text("")
            Text("")
            Spacer()
            Spacer()
            Text("")
            Spacer()
            Text("")
            Spacer()
            Button(action: { }) {
                Text(" ")
            }
            Text("Block Contact Manually")
            Text("")
            Text("").navigationTitle("FreezeReflexFragment")
        }.onAppear { viewModel.onEvent(FreezeReflexFragmentEvent.onAppear) }
    }
}
