import SwiftUI

struct GuardianNotificationServiceScreen: View {
    @EnvironmentObject var container: CodexiaContainer
    
    var body: some View {
        VStack(spacing: 20) {
            Text("Momma Mobile: GuardianNotificationService").font(.title).bold()
            Text("GuardianNotificationService")
            Text("guardian_service")
            Text("GuardianNotificationService created")
            Text("No guardian logged in, service will wait for authentication")
            Text("Service started")
            Text("Service destroyed, removing listeners")
            Text("Guardian Monitoring Service")
            Text("Keeps Momma Mobile monitoring active")
            Text("momma_critical")
            Text("Critical Alerts")
            Text("Critical threats and FreezeReflex activations")
            Text("momma_high")
            Text("High Priority Alerts")
            Text("Blocked contact attempts and high severity threats")
            Text("momma_medium")
            Text("Medium Priority Alerts")
            Text("Medium severity threats")
            Text("momma_info")
            Text("Information")
            Text("General information and updates")
            Text("Momma Mobile Active")
            Text("Monitoring for threats and protecting your child")
            Text("Setting up Firebase listeners for guardian: $guardianId")
            Text("guardians/$guardianId/children")
            Text("Error getting children list: ${error.message}")
            Text("Setting up listeners for child: $childId")
            Text("freezeReflex/$guardianId/$childId/conversations")
            Text("FreezeReflex listener cancelled: ${error.message}")
            Text("freezeReflex/$guardianId/$childId/blockedAttempts")
            Text("Blocked attempts listener cancelled: ${error.message}")
            Text("detections/$guardianId/$childId")
            Text("Detections listener cancelled: ${error.message}")
            Text("source")
            Text("message")
            Text("severity")
            Text("category")
            Text("timestamp")
            Text("FreezeReflex activated for child $childId: $category from $source")
            Text("Error handling FreezeReflex activation")
            Text("source")
            Text("message")
            Text("timestamp")
            Text("Blocked attempt for child $childId from $source")
            Text("Error handling blocked attempt")
            Text("category")
            Text("severity")
            Text("message")
            Text("timestamp")
            Text("HIGH")
            Text("Threat detected for child $childId: $category ($severity)")
            Text("Error handling threat detection")
            Text("children/$childId/name")
            Text("Your child")
            Text("Your child")
            Text("open_tab")
            Text("momma_critical")
            Text("🚨 FreezeReflex Activated - $childName")
            Text("Blocked dangerous contact: $source")
            Text("Category: $category\\nContact: $source\\n\\nMessage: $message\\n\\n✅ App frozen, contact blocked, auto-takeover enabled.")
            Text("open_tab")
            Text("momma_high")
            Text("🚫 Blocked Contact Attempted - $childName")
            Text("$source tried to message")
            Text("Blocked contact: $source\\n\\nAttempted message: $message\\n\\n✅ Auto-blocked by FreezeReflex. MommaTakeover sent deflection response.")
            Text("open_tab")
            Text("CRITICAL")
            Text("CRITICAL")
            Text("CRITICAL")
            Text("$icon Threat Detected - $childName")
            Text("$category\\n\\n$message")
            Text("CRITICAL")
            Spacer()
        }.padding()
        .navigationTitle("GuardianNotificationService")
    }
}