import SwiftUI

struct HeartbeatMonitorServiceScreen: View {
    @EnvironmentObject var container: CodexiaContainer
    
    var body: some View {
        VStack(spacing: 20) {
            Text("Momma Mobile: HeartbeatMonitorService").font(.title).bold()
            Text("HeartbeatMonitor")
            Text("HeartbeatMonitorService created")
            Text("HeartbeatMonitorService started")
            Text("Guardian not authenticated, cannot monitor heartbeats")
            Text("✅ Heartbeat monitoring started (checking every 2 minutes)")
            Text("guardianLinks/$guardianId/linkedChildren")
            Text("last_seen")
            Text("nickname")
            Text("uninstall_imminent")
            Text("offline_alert_sent")
            Text("🚨 CRITICAL: Child $childId ($nickname) has disabled Device Admin - uninstall imminent!")
            Text("offline_alert_sent")
            Text("⚠️ Child $childId ($nickname) hasn't reported in ${timeSinceLastSeen / 1000 / 60} minutes")
            Text("offline_alert_sent")
            Text("offline_alert_sent")
            Text("✅ Child $childId ($nickname) is back online")
            Text("Failed to check heartbeats: ${error.message}")
            Text("flags/$guardianId/$childId")
            Text("severity")
            Text("message")
            Text("timestamp")
            Text("type")
            Text("actionRequired")
            Text("lastSeen")
            Text("minutesOffline")
            Text("✅ Offline alert sent for child $childId")
            Text("❌ Failed to send offline alert: ${error.message}")
            Text("logs/$guardianId/$childId")
            Text("event")
            Text("timestamp")
            Text("severity")
            Text("message")
            Text("lastSeen")
            Text("flags/$guardianId/$childId")
            Text("severity")
            Text("message")
            Text("timestamp")
            Text("type")
            Text("actionRequired")
            Text("lastSeen")
            Text("✅ Uninstall imminent alert sent for child $childId")
            Text("❌ Failed to send uninstall imminent alert: ${error.message}")
            Text("logs/$guardianId/$childId")
            Text("event")
            Text("timestamp")
            Text("severity")
            Text("message")
            Text("lastSeen")
            Text("HeartbeatMonitorService destroyed")
            Spacer()
        }.padding()
        .navigationTitle("HeartbeatMonitorService")
    }
}