import SwiftUI

struct HomeScreen: View {
    private let screenNames = ["Awaiting Partner Screen","Billing Manager","Browse Members Screen","Candidate Analysis","Candidate Comparison","Candidate Invitation","Candidate Invitation Screen","Candidate Invitation Service","Candidate Quiz Screen","Candidate Waiting Screen","Chat Screen","Children Desire","Cloudinary Config","Color","Communication Vector","Compatibility Breakdown","Compatibility Engine","Compatibility Score","Compatibility Vector","Conflict Style","Conflict Vector","Conversation","Conversation Item","Decision Factor","Elimination Screen","Final Selection Screen","Future Vector","Gender","Ghost Detection Result","Ghost Detection Service","Ghost Detection Worker","Ghost Detection Worker_ Hilt Module","Home Screen","Invitation Item","Invitation Status","Location","Location Service","Match","Match Candidate","Match Filter","Match History Item","Match History Screen","Match Outcome","Match Phase","Match Profile Card","Match Statistics","Match Status","Match Success Screen","Matching Service","Message","Message Type","Nav Graph","Notifications Screen","Orientation","Partner Decision Screen","Partner Response","Payment","Payment Screen","Payment Status","Philosophy Vector","Photo Moderation Status","Product Details","Profile Screen","Profile Setup Screen","Progress Bar","Push Notification Service","Question","Question Answer","Question Card","Question Category","Question Database","Question Option","Question Type","Questionnaire Response","Questionnaire Screen","Quiz Category","Quiz Option","Quiz Question","Quiz Question Data","Quiz Question Database","Quiz Result","Quiz Scorer","Quiz Screen","Ranked Candidate","Search Session","Second Chance Reason","Second Chance Screen","Selection Analysis","Sign In Screen","Sign Up Screen","Soul Link Application","Soul Link Application_ Component Tree Deps","Soul Link Application_ Hilt Components","Soul Link Message","Soul Link Messaging Service","Soul Link Personality","Splash Screen","The Three Screen","Theme","Tuple4","Type","User","User Profile Screen","Values Vector","Vector Mapping","Welcome Screen"];

    var body: some View {
        NavigationView {
            List(screenNames, id: \.self) { name in
                NavigationLink(name, destination: destination(for: name))
            }
            .navigationTitle("Dashboard")
        }
    }

    @ViewBuilder
    private func destination(for name: String) -> some View {
        switch name {
        case "Awaiting Partner Screen": AwaitingPartnerScreenScreen()
        case "Billing Manager": BillingManagerScreen()
        case "Browse Members Screen": BrowseMembersScreenScreen()
        case "Candidate Analysis": CandidateAnalysisScreen()
        case "Candidate Comparison": CandidateComparisonScreen()
        case "Candidate Invitation": CandidateInvitationScreen()
        case "Candidate Invitation Screen": CandidateInvitationScreenScreen()
        case "Candidate Invitation Service": CandidateInvitationServiceScreen()
        case "Candidate Quiz Screen": CandidateQuizScreenScreen()
        case "Candidate Waiting Screen": CandidateWaitingScreenScreen()
        case "Chat Screen": ChatScreenScreen()
        case "Children Desire": ChildrenDesireScreen()
        case "Cloudinary Config": CloudinaryConfigScreen()
        case "Color": ColorScreen()
        case "Communication Vector": CommunicationVectorScreen()
        case "Compatibility Breakdown": CompatibilityBreakdownScreen()
        case "Compatibility Engine": CompatibilityEngineScreen()
        case "Compatibility Score": CompatibilityScoreScreen()
        case "Compatibility Vector": CompatibilityVectorScreen()
        case "Conflict Style": ConflictStyleScreen()
        case "Conflict Vector": ConflictVectorScreen()
        case "Conversation": ConversationScreen()
        case "Conversation Item": ConversationItemScreen()
        case "Decision Factor": DecisionFactorScreen()
        case "Elimination Screen": EliminationScreenScreen()
        case "Final Selection Screen": FinalSelectionScreenScreen()
        case "Future Vector": FutureVectorScreen()
        case "Gender": GenderScreen()
        case "Ghost Detection Result": GhostDetectionResultScreen()
        case "Ghost Detection Service": GhostDetectionServiceScreen()
        case "Ghost Detection Worker": GhostDetectionWorkerScreen()
        case "Ghost Detection Worker_ Hilt Module": GhostDetectionWorker_HiltModuleScreen()
        case "Home Screen": HomeScreenScreen()
        case "Invitation Item": InvitationItemScreen()
        case "Invitation Status": InvitationStatusScreen()
        case "Location": LocationScreen()
        case "Location Service": LocationServiceScreen()
        case "Match": MatchScreen()
        case "Match Candidate": MatchCandidateScreen()
        case "Match Filter": MatchFilterScreen()
        case "Match History Item": MatchHistoryItemScreen()
        case "Match History Screen": MatchHistoryScreenScreen()
        case "Match Outcome": MatchOutcomeScreen()
        case "Match Phase": MatchPhaseScreen()
        case "Match Profile Card": MatchProfileCardScreen()
        case "Match Statistics": MatchStatisticsScreen()
        case "Match Status": MatchStatusScreen()
        case "Match Success Screen": MatchSuccessScreenScreen()
        case "Matching Service": MatchingServiceScreen()
        case "Message": MessageScreen()
        case "Message Type": MessageTypeScreen()
        case "Nav Graph": NavGraphScreen()
        case "Notifications Screen": NotificationsScreenScreen()
        case "Orientation": OrientationScreen()
        case "Partner Decision Screen": PartnerDecisionScreenScreen()
        case "Partner Response": PartnerResponseScreen()
        case "Payment": PaymentScreen()
        case "Payment Screen": PaymentScreenScreen()
        case "Payment Status": PaymentStatusScreen()
        case "Philosophy Vector": PhilosophyVectorScreen()
        case "Photo Moderation Status": PhotoModerationStatusScreen()
        case "Product Details": ProductDetailsScreen()
        case "Profile Screen": ProfileScreenScreen()
        case "Profile Setup Screen": ProfileSetupScreenScreen()
        case "Progress Bar": ProgressBarScreen()
        case "Push Notification Service": PushNotificationServiceScreen()
        case "Question": QuestionScreen()
        case "Question Answer": QuestionAnswerScreen()
        case "Question Card": QuestionCardScreen()
        case "Question Category": QuestionCategoryScreen()
        case "Question Database": QuestionDatabaseScreen()
        case "Question Option": QuestionOptionScreen()
        case "Question Type": QuestionTypeScreen()
        case "Questionnaire Response": QuestionnaireResponseScreen()
        case "Questionnaire Screen": QuestionnaireScreenScreen()
        case "Quiz Category": QuizCategoryScreen()
        case "Quiz Option": QuizOptionScreen()
        case "Quiz Question": QuizQuestionScreen()
        case "Quiz Question Data": QuizQuestionDataScreen()
        case "Quiz Question Database": QuizQuestionDatabaseScreen()
        case "Quiz Result": QuizResultScreen()
        case "Quiz Scorer": QuizScorerScreen()
        case "Quiz Screen": QuizScreenScreen()
        case "Ranked Candidate": RankedCandidateScreen()
        case "Search Session": SearchSessionScreen()
        case "Second Chance Reason": SecondChanceReasonScreen()
        case "Second Chance Screen": SecondChanceScreenScreen()
        case "Selection Analysis": SelectionAnalysisScreen()
        case "Sign In Screen": SignInScreenScreen()
        case "Sign Up Screen": SignUpScreenScreen()
        case "Soul Link Application": SoulLinkApplicationScreen()
        case "Soul Link Application_ Component Tree Deps": SoulLinkApplication_ComponentTreeDepsScreen()
        case "Soul Link Application_ Hilt Components": SoulLinkApplication_HiltComponentsScreen()
        case "Soul Link Message": SoulLinkMessageScreen()
        case "Soul Link Messaging Service": SoulLinkMessagingServiceScreen()
        case "Soul Link Personality": SoulLinkPersonalityScreen()
        case "Splash Screen": SplashScreenScreen()
        case "The Three Screen": TheThreeScreenScreen()
        case "Theme": ThemeScreen()
        case "Tuple4": Tuple4Screen()
        case "Type": TypeScreen()
        case "User": UserScreen()
        case "User Profile Screen": UserProfileScreenScreen()
        case "Values Vector": ValuesVectorScreen()
        case "Vector Mapping": VectorMappingScreen()
        case "Welcome Screen": WelcomeScreenScreen()
        default:
            Text(name)
        }
    }
}