
import SwiftUI

struct HomeScreen: View {
    @AppStorage("isLoggedIn") var isLoggedIn = true
    var body: some View {
        NavigationView {
            ZStack {
                // Background Mascot Image (Name this "MommaDashBackground" in Xcode)
                Image("MommaDashBackground")
                    .resizable()
                    .scaledToFill()
                    .edgesIgnoringSafeArea(.all)
                
                ScrollView {
                    VStack(spacing: 12) {
                        Spacer().frame(height: 60)
                        ForEach(["LINK CHILD DEVICE","RECENT","FLAGGED","FREEZE","LINKED","MASCOT","SCANNER","PLATFORMS","SMS","LOCATION","CONSENT"], id: \.self) { btn in
                            NavigationLink(destination: AnyViewByName(name: btn)) {
                                Text(btn)
                                    .font(.system(size: 18, weight: .black, design: .monospaced))
                                    .foregroundColor(.white)
                                    .multilineTextAlignment(.center)
                                    .frame(width: 240, height: 55)
                                    .background(Color.purple)
                                    .cornerRadius(6)
                                    .shadow(color: .black.opacity(0.3), radius: 4, x: 0, y: 4)
                            }
                        }
                    }
                    .frame(maxWidth: .infinity, alignment: .trailing)
                    .padding(.trailing, 25)
                }
            }
        }
    }
}

struct AnyViewByName: View {
    let name: String
    var body: some View {
        let normalized = name.lowercased().replacingOccurrences(of: " ", with: "")
        switch normalized {
        case "linkchilddevice": LinkChildDeviceScreen()
        case "scanner": ScannerScreen()
        case "location": LocationScreen()
        case "admindeactivationmonitor": AdminDeactivationMonitorScreen()
        case "appblockerservice": AppBlockerServiceScreen()
        case "appscopetoggle": AppScopeToggleScreen()
        case "autohideprovider": AutoHideProviderScreen()
        case "blockedappactivity": BlockedAppActivityScreen()
        case "blockedcontact": BlockedContactScreen()
        case "blockedwebsiteactivity": BlockedWebsiteActivityScreen()
        case "bootreceiver": BootReceiverScreen()
        case "childlinkactivity": ChildLinkActivityScreen()
        case "childselector": ChildSelectorScreen()
        case "childsyncservice": ChildSyncServiceScreen()
        case "color": ColorScreen()
        case "composeplatformcontrolfragment": ComposePlatformControlFragmentScreen()
        case "consentmanagementactivity": ConsentManagementActivityScreen()
        case "consentmodal": ConsentModalScreen()
        case "consentoverviewactivity": ConsentOverviewActivityScreen()
        case "consentoverviewfragment": ConsentOverviewFragmentScreen()
        case "consentoverviewtab": ConsentOverviewTabScreen()
        case "emotionalpatternloader": EmotionalPatternLoaderScreen()
        case "emotionalradar": EmotionalRadarScreen()
        case "emotionalscanner": EmotionalScannerScreen()
        case "escalationmatrix": EscalationMatrixScreen()
        case "exampleinstrumentedtest": ExampleInstrumentedTestScreen()
        case "exampleunittest": ExampleUnitTestScreen()
        case "factoryresetdetector": FactoryResetDetectorScreen()
        case "feelscopeservice": FeelScopeServiceScreen()
        case "firebaseextensions": FirebaseExtensionsScreen()
        case "firebaselogger": FirebaseLoggerScreen()
        case "firebasesync": FirebaseSyncScreen()
        case "flag": FlagScreen()
        case "flaggedmessage": FlaggedMessageScreen()
        case "flaggedmessageadapter": FlaggedMessageAdapterScreen()
        case "flaggedmessagesactivity": FlaggedMessagesActivityScreen()
        case "flaggedmessagesfragment": FlaggedMessagesFragmentScreen()
        case "flaggedmessagestab": FlaggedMessagesTabScreen()
        case "freezereflex": FreezeReflexScreen()
        case "freezereflexfragment": FreezeReflexFragmentScreen()
        case "freezereflextab": FreezeReflexTabScreen()
        case "freezereflexwarningactivity": FreezeReflexWarningActivityScreen()
        case "generatelinkqractivity": GenerateLinkQrActivityScreen()
        case "guardiandashboard": GuardianDashboardScreen()
        case "guardiannotificationservice": GuardianNotificationServiceScreen()
        case "guardiantabadapter": GuardianTabAdapterScreen()
        case "harmfulpatterns": HarmfulPatternsScreen()
        case "heartbeatmonitorservice": HeartbeatMonitorServiceScreen()
        case "linkedchildrenactivity": LinkedChildrenActivityScreen()
        case "linkedchildrenfragment": LinkedChildrenFragmentScreen()
        case "linkedchildrentab": LinkedChildrenTabScreen()
        case "locationstatusactivity": LocationStatusActivityScreen()
        case "locationstatusfragment": LocationStatusFragmentScreen()
        case "locationstatustab": LocationStatusTabScreen()
        case "locationsync": LocationSyncScreen()
        case "locationtrackerservice": LocationTrackerServiceScreen()
        case "loginactivity": LoginActivityScreen()
        case "mainactivity": MainActivityScreen()
        case "mainapplication": MainApplicationScreen()
        case "mascotmood": MascotMoodScreen()
        case "mascotmoodactivity": MascotMoodActivityScreen()
        case "mascotmoodfragment": MascotMoodFragmentScreen()
        case "mascotmoodtab": MascotMoodTabScreen()
        case "messagenotificationlistener": MessageNotificationListenerScreen()
        case "messagescanneractivity": MessageScannerActivityScreen()
        case "messagescannerfragment": MessageScannerFragmentScreen()
        case "messagescannertab": MessageScannerTabScreen()
        case "mommadeviceadmin": MommaDeviceAdminScreen()
        case "mommamobiletheme": MommaMobileThemeScreen()
        case "mommanotificationservice": MommaNotificationServiceScreen()
        case "mommatakeover": MommaTakeoverScreen()
        case "nettiedeviceadminreceiver": NettieDeviceAdminReceiverScreen()
        case "nettieprotectionservice": NettieProtectionServiceScreen()
        case "onlinesafetyactivity": OnlineSafetyActivityScreen()
        case "onlinesafetyfragment": OnlineSafetyFragmentScreen()
        case "onlinesafetytab": OnlineSafetyTabScreen()
        case "platformcontrolactivity": PlatformControlActivityScreen()
        case "platformcontrolreceiver": PlatformControlReceiverScreen()
        case "platformcontroltab": PlatformControlTabScreen()
        case "platformenforcementservice": PlatformEnforcementServiceScreen()
        case "qrutils": QRUtilsScreen()
        case "recentdetectionsactivities": RecentDetectionsActivitiesScreen()
        case "recentdetectionsfragment": RecentDetectionsFragmentScreen()
        case "recentdetectionstab": RecentDetectionsTabScreen()
        case "safescope": SafeScopeScreen()
        case "safescopefragment": SafeScopeFragmentScreen()
        case "safescopetoggle": SafeScopeToggleScreen()
        case "safescopevpnservice": SafeScopeVpnServiceScreen()
        case "scannerengine": ScannerEngineScreen()
        case "scannerglobals": ScannerGlobalsScreen()
        case "servicestarter": ServiceStarterScreen()
        case "setupactivity": SetupActivityScreen()
        case "setup": SetupScreen()
        case "smscomposeactivity": SmsComposeActivityScreen()
        case "smsdetectionsactivity": SmsDetectionsActivityScreen()
        case "smsdetectionsfragment": SmsDetectionsFragmentScreen()
        case "smsdetectionstab": SmsDetectionsTabScreen()
        case "smsinboxactivity": SmsInboxActivityScreen()
        case "smsreceiver": SmsReceiverScreen()
        case "subscriptionexpiredactivity": SubscriptionExpiredActivityScreen()
        case "subscriptionexpired": SubscriptionExpiredScreen()
        case "subscriptionmanager": SubscriptionManagerScreen()
        case "theme": ThemeScreen()
        case "type": TypeScreen()
        case "uninstallattemptmonitor": UninstallAttemptMonitorScreen()
        case "vpnpermissionactivity": VpnPermissionActivityScreen()
        case "websiteblockerservice": WebsiteBlockerServiceScreen()
        default: Text("Module Logic: Active")
        }
    }
}
