import SwiftUI

struct LinkedChildrenTabScreen: View {
    @EnvironmentObject var container: CodexiaContainer
    
    var body: some View {
        VStack(spacing: 20) {
            Text("Momma Mobile: LinkedChildrenTab").font(.title).bold()
            Text("Action")
            Text("Action")
            Text("Unnamed")
            Text("unknown")
            Text("LinkedChildrenTab")
            Text("LinkedChildrenTab")
            Text("LinkedChildrenTab")
            Text("LinkedChildrenTab")
            Text("LinkedChildrenTab")
            Text("LinkedChildrenTab")
            Text("LinkedChildrenTab")
            Text("guardianLinks/$guardianId/linkedChildren")
            Text("LinkedChildrenTab")
            Text("LinkedChildrenTab")
            Text("LinkedChildrenTab")
            Text("LinkedChildrenTab")
            Text("LinkedChildrenTab")
            Text("nickname")
            Text("mood")
            Text("last_seen")
            Text("isEscalated")
            Text("deviceAdminEnabled")
            Text("LinkedChildrenTab")
            Text("LinkedChildrenTab")
            Text("LinkedChildrenTab")
            Text("LinkedChildrenTab")
            Text("LinkedChildrenTab")
            Text("LinkedChildrenTab")
            Text("LinkedChildrenTab")
            Text("LinkedChildrenTab")
            Text("LinkedChildrenTab")
            Text("LinkedChildrenTab")
            Text("LinkedChildrenTab")
            Text("Linked Children")
            Text("No children linked yet. Use the 'Link Child Device' tab to generate a QR code.")
            Text("👤 Name: ${child.name}")
            Text("🎭 Mood: ${child.mood}")
            Text("🕒 Last Seen: ${DateFormat.getDateTimeInstance().format(child.lastSeen)}")
            Text("🔒 Device Admin: ${if (child.deviceAdminEnabled) ")
            Button("Action") { /* Trigger Event */ }
            Text("🚨 Freeze")
            Button("Action") { /* Trigger Event */ }
            Text("🔓 Deactivate Admin")
            Text("⚠️ Confirm Admin Deactivation")
            Text("Action")
            Text("This will request the child device to deactivate Device Admin protection.")
            Text("⚠️ WARNING: This may allow the child to uninstall the app!")
            Text("Enter your guardian password to confirm:")
            TextField("Action", text: .constant(""))
                .textFieldStyle(.roundedBorder)
            Text("Password")
            Text("Action")
            Text("Action")
            Button("Action") { /* Trigger Event */ }
            Text("LinkedChildrenTab")
            Text("LinkedChildrenTab")
            Text("Confirm")
            Text("Cancel")
            Text("Guardian not authenticated")
            Text("Password cannot be empty")
            Text("Guardian email not found")
            Text("LinkedChildrenTab")
            Text("guardianLinks/$guardianId/linkedChildren/$childId/adminDeactivationRequested")
            Text("LinkedChildrenTab")
            Text("guardianLinks/$guardianId/linkedChildren/$childId/adminDeactivationAuthorized")
            Text("LinkedChildrenTab")
            Text("logs/$guardianId/$childId")
            Text("event")
            Text("timestamp")
            Text("severity")
            Text("message")
            Text("LinkedChildrenTab")
            Text("Failed to send request: ${error.message}")
            Text("LinkedChildrenTab")
            Text("Incorrect password")
            Spacer()
        }.padding()
        .navigationTitle("LinkedChildrenTab")
    }
}