import SwiftUI

struct MommaDeviceAdminScreen: View {
    @EnvironmentObject var container: CodexiaContainer
    
    var body: some View {
        VStack(spacing: 20) {
            Text("Momma Mobile: MommaDeviceAdmin").font(.title).bold()
            Text("MommaDeviceAdmin")
            Text("✅ Device Admin ENABLED - App is now protected from uninstallation")
            Text("enabled")
            Text("⚠️ Device Admin DISABLED - App can now be uninstalled!")
            Text("disabled")
            Text("⚠️ Child is attempting to disable Device Admin!")
            Text("⚠️ Disabling this will alert your guardian and may violate your safety agreement.")
            Text("nettie_prefs")
            Text("guardian_id")
            Text("child_id")
            Text("logs/$guardianId/$childId")
            Text("event")
            Text("timestamp")
            Text("severity")
            Text("message")
            Text("nettie_prefs")
            Text("guardian_id")
            Text("child_id")
            Text("flags/$guardianId/$childId")
            Text("severity")
            Text("message")
            Text("timestamp")
            Text("type")
            Text("actionRequired")
            Text("nettie_prefs")
            Text("guardian_id")
            Text("child_id")
            Text("flags/$guardianId/$childId")
            Text("severity")
            Text("message")
            Text("timestamp")
            Text("type")
            Text("nettie_prefs")
            Text("guardian_id")
            Text("child_id")
            Text("guardianLinks/$guardianId/linkedChildren/$childId")
            Text("last_seen")
            Text("uninstall_imminent")
            Text("⚠️ Final heartbeat sent - uninstall imminent flag set")
            Spacer()
        }.padding()
        .navigationTitle("MommaDeviceAdmin")
    }
}