import SwiftUI

struct MommaNotificationServiceScreen: View {
    @EnvironmentObject var container: CodexiaContainer
    
    var body: some View {
        VStack(spacing: 20) {
            Text("Momma Mobile: MommaNotificationService").font(.title).bold()
            Text("MommaNotifications")
            Text("freezereflex_critical")
            Text("freezereflex_high")
            Text("freezereflex_medium")
            Text("freezereflex_info")
            Text("📱 New FCM token: $token")
            Text("📨 Message received from: ${message.from}")
            Text("severity")
            Text("type")
            Text("childName")
            Text("threat")
            Text("contact")
            Text("category")
            Text("message")
            Text("🚨 Notification type: $type, severity: $severity")
            Text("freezereflex_activated")
            Text("blocked_attempt")
            Text("threat_detected")
            Text("title")
            Text("body")
            Text("critical")
            Text("high")
            Text("open_tab")
            Text("🚨 FreezeReflex Activated - $childName")
            Text("Blocked dangerous contact: $contact")
            Text("Category: $category\\nContact: $contact\\n\\nMessage: $message\\n\\n✅ App frozen, contact blocked, auto-takeover enabled.")
            Text("View Details")
            Text("✅ FreezeReflex activation notification sent")
            Text("open_tab")
            Text("🚫 Blocked Contact Attempted - $childName")
            Text("$contact tried to message")
            Text("Blocked contact: $contact\\n\\nAttempted message: $message\\n\\n✅ Auto-blocked by FreezeReflex. MommaTakeover sent deflection response.")
            Text("✅ Blocked attempt notification sent")
            Text("critical")
            Text("high")
            Text("medium")
            Text("open_tab")
            Text("⚠️ Threat Detected - $childName")
            Text("critical")
            Text("high")
            Text("✅ Threat detected notification sent")
            Text("critical")
            Text("high")
            Text("medium")
            Text("✅ Generic notification sent")
            Text("Critical Alerts")
            Text("Critical threats that triggered FreezeReflex")
            Text("High Priority Alerts")
            Text("Blocked contact attempts and high-priority threats")
            Text("Medium Priority Alerts")
            Text("Medium-priority threats and detections")
            Text("Information")
            Text("General information and updates")
            Text("✅ Notification channels created")
            Text("users/$userId/fcmToken")
            Text("✅ FCM token saved to Firebase for user: $userId")
            Text("❌ Failed to save FCM token: ${e.message}")
            Text("⚠️ Cannot save FCM token - user not logged in")
            Text("❌ Error saving FCM token: ${e.message}")
            Spacer()
        }.padding()
        .navigationTitle("MommaNotificationService")
    }
}