import SwiftUI

struct NavGraphScreen: View {
    @StateObject private var viewModel = NavGraphViewModel()

    var body: some View {
        NavigationView {
            ZStack {
                CodexiaTheme.background.ignoresSafeArea()
            Text("\\u0000\\u0016\\n\\u0000\\n\\u0002\\u0010\\u0002\\n\\u0000\\n\\u0002\\u0018\\u0002\\n\\u0000\\n\\u0002\\u0010\\u000e\\n\\u0002\\b\\u0002\\u001a!\\u0010\\u0000\\u001a\\u00020\\u00012\\b\\b\\u0002\\u0010\\u0002\\u001a\\u00020\\u00032\\b\\b\\u0002\\u0010\\u0004\\u001a\\u00020\\u0005H\\u0007¢\\u0006\\u0002\\u0010\\u0006¨\\u0006\\u0007")
            Text("C(SoulLinkNavGraph)46@1946L23,49@2030L12334:NavGraph.kt#9xlij7")
            Text("com.soullink.app.ui.navigation.SoulLinkNavGraph (NavGraph.kt:48)")
            Text("it")
            Text("C54@2219L3266:NavGraph.kt#9xlij7")
            Text("com.soullink.app.ui.navigation.SoulLinkNavGraph.<anonymous>.<anonymous> (NavGraph.kt:54)")
            Text("search")
            Text("it")
            Text("C129@5588L28:NavGraph.kt#9xlij7")
            Text("com.soullink.app.ui.navigation.SoulLinkNavGraph.<anonymous>.<anonymous> (NavGraph.kt:129)")
            Text("it")
            Text("C133@5715L27:NavGraph.kt#9xlij7")
            Text("com.soullink.app.ui.navigation.SoulLinkNavGraph.<anonymous>.<anonymous> (NavGraph.kt:133)")
            Text("it")
            Text("C137@5841L27:NavGraph.kt#9xlij7")
            Text("com.soullink.app.ui.navigation.SoulLinkNavGraph.<anonymous>.<anonymous> (NavGraph.kt:137)")
            Text("it")
            Text("C141@5976L33:NavGraph.kt#9xlij7")
            Text("com.soullink.app.ui.navigation.SoulLinkNavGraph.<anonymous>.<anonymous> (NavGraph.kt:141)")
            Text("it")
            Text("C145@6112L332:NavGraph.kt#9xlij7")
            Text("com.soullink.app.ui.navigation.SoulLinkNavGraph.<anonymous>.<anonymous> (NavGraph.kt:145)")
            Text("it")
            Text("C158@6559L34:NavGraph.kt#9xlij7")
            Text("com.soullink.app.ui.navigation.SoulLinkNavGraph.<anonymous>.<anonymous> (NavGraph.kt:158)")
            Text("paymentType")
            Text("contextId")
            Text("backStackEntry")
            Text("C178@7317L156:NavGraph.kt#9xlij7")
            Text("com.soullink.app.ui.navigation.SoulLinkNavGraph.<anonymous>.<anonymous> (NavGraph.kt:175)")
            Text("paymentType")
            Text("search")
            Text("contextId")
            Text("backStackEntry")
            Text("C186@7618L761:NavGraph.kt#9xlij7")
            Text("com.soullink.app.ui.navigation.SoulLinkNavGraph.<anonymous>.<anonymous> (NavGraph.kt:186)")
            Text("invitationId")
            Text("candidate")
            Text("it")
            Text("C206@8571L262:NavGraph.kt#9xlij7")
            Text("com.soullink.app.ui.navigation.SoulLinkNavGraph.<anonymous>.<anonymous> (NavGraph.kt:206)")
            Text("it")
            Text("C216@8948L349:NavGraph.kt#9xlij7")
            Text("com.soullink.app.ui.navigation.SoulLinkNavGraph.<anonymous>.<anonymous> (NavGraph.kt:216)")
            Text("it")
            Text("C229@9408L246:NavGraph.kt#9xlij7")
            Text("com.soullink.app.ui.navigation.SoulLinkNavGraph.<anonymous>.<anonymous> (NavGraph.kt:229)")
            Text("it")
            Text("C239@9759L29:NavGraph.kt#9xlij7")
            Text("com.soullink.app.ui.navigation.SoulLinkNavGraph.<anonymous>.<anonymous> (NavGraph.kt:239)")
            Text("it")
            Text("C243@9885L25:NavGraph.kt#9xlij7")
            Text("com.soullink.app.ui.navigation.SoulLinkNavGraph.<anonymous>.<anonymous> (NavGraph.kt:243)")
            Text("it")
            Text("C247@10027L35:NavGraph.kt#9xlij7")
            Text("com.soullink.app.ui.navigation.SoulLinkNavGraph.<anonymous>.<anonymous> (NavGraph.kt:247)")
            Text("it")
            Text("C251@10174L36:NavGraph.kt#9xlij7")
            Text("com.soullink.app.ui.navigation.SoulLinkNavGraph.<anonymous>.<anonymous> (NavGraph.kt:251)")
            Text("it")
            Text("C255@10329L36:NavGraph.kt#9xlij7")
            Text("com.soullink.app.ui.navigation.SoulLinkNavGraph.<anonymous>.<anonymous> (NavGraph.kt:255)")
            Text("it")
            Text("C259@10478L33:NavGraph.kt#9xlij7")
            Text("com.soullink.app.ui.navigation.SoulLinkNavGraph.<anonymous>.<anonymous> (NavGraph.kt:259)")
            Text("it")
            Text("C263@10608L25:NavGraph.kt#9xlij7")
            Text("com.soullink.app.ui.navigation.SoulLinkNavGraph.<anonymous>.<anonymous> (NavGraph.kt:263)")
            Text("it")
            Text("C267@10746L502:NavGraph.kt#9xlij7")
            Text("com.soullink.app.ui.navigation.SoulLinkNavGraph.<anonymous>.<anonymous> (NavGraph.kt:267)")
            Text("it")
            Text("C282@11345L1672:NavGraph.kt#9xlij7")
            Text("com.soullink.app.ui.navigation.SoulLinkNavGraph.<anonymous>.<anonymous> (NavGraph.kt:282)")
            Text("matchId")
            Text("paymentType")
            Text("contextId")
            Text("it")
            Text("C323@13132L291:NavGraph.kt#9xlij7")
            Text("com.soullink.app.ui.navigation.SoulLinkNavGraph.<anonymous>.<anonymous> (NavGraph.kt:323)")
            Text("invitationId")
            Text("it")
            Text("C334@13538L292:NavGraph.kt#9xlij7")
            Text("com.soullink.app.ui.navigation.SoulLinkNavGraph.<anonymous>.<anonymous> (NavGraph.kt:334)")
            Text("userId")
            Text("userId")
            Text("backStackEntry")
            Text("C351@14181L167:NavGraph.kt#9xlij7")
            Text("com.soullink.app.ui.navigation.SoulLinkNavGraph.<anonymous>.<anonymous> (NavGraph.kt:350)")
            Text("userId")
            }
            .navigationTitle("Nav Graph")
            .foregroundStyle(CodexiaTheme.label)
        }
        .onAppear { viewModel.onEvent(NavGraphEvent.onAppear) }
    }
}
