import SwiftUI

struct PlatformControlTabScreen: View {
    @EnvironmentObject var container: CodexiaContainer
    
    var body: some View {
        VStack(spacing: 20) {
            Text("Momma Mobile: PlatformControlTab").font(.title).bold()
            Text("Action")
            Text("Action")
            Text("Discord")
            Text("📄 Share stories of online safety wins...")
            Text("guardianLinks/$guardianId/linkedChildren")
            Text("PlatformControlTab")
            Text("guardianLinks/$guardianId/linkedChildren/$childId")
            Text("guardianLinks/$guardianId/platformControls/$childId")
            Text("nickname")
            Text("dob")
            Text("MM/dd/yyyy")
            Text("PlatformControlTab")
            Text("PlatformControlTab")
            Text("guardianLinks/$guardianId/emergencyContacts")
            Text("police")
            Text("school")
            Text("sheriff")
            Text("Emergency Contacts")
            TextField("Action", text: .constant(""))
                .textFieldStyle(.roundedBorder)
            Text("guardianLinks/$guardianId/emergencyContacts/police")
            Text("Local Police Dept")
            Text("(555) 555-1212")
            TextField("Action", text: .constant(""))
                .textFieldStyle(.roundedBorder)
            Text("guardianLinks/$guardianId/emergencyContacts/school")
            Text("Local School")
            Text("(555) 555-3434")
            TextField("Action", text: .constant(""))
                .textFieldStyle(.roundedBorder)
            Text("guardianLinks/$guardianId/emergencyContacts/sheriff")
            Text("Sheriff")
            Text("(555) 555-9876")
            Text("Platform Controls")
            Text("Action")
            Toggle("Action", isOn: .constant(true))
            Toggle("Action", isOn: .constant(true))
            Text("guardianLinks/$guardianId/platformControls/$childId/$key")
            Text("Failed to update $platform")
            Text("Action")
            Text("Toggles above control both access and Nettie’s emotional radar per platform.")
            Text("guardianLinks/$guardianId/linkedChildren/$childId")
            Text("Child Profile")
            Text("🎉 Happy Birthday, $nickname! 🎂")
            TextField("Action", text: .constant(""))
                .textFieldStyle(.roundedBorder)
            Text("nickname")
            Text("Child's Name")
            TextField("Action", text: .constant(""))
                .textFieldStyle(.roundedBorder)
            Text("dob")
            Text("Date of Birth (MM/DD/YYYY)")
            Text("e.g., 01/23/2010")
            Text("guardian_profiles/$guardianId/consent/$childId")
            Text("granted")
            Text("ConsentSection")
            Text("Consent & Emotional Monitoring")
            Text("By granting consent, you allow Nettie to:")
            Text("• Monitor emotional signals across supported platforms (SMS, Discord, Roblox, etc.)")
            Text("• Detect harmful patterns and escalate when needed")
            Text("• Share emotional insights with you through the guardian dashboard")
            Text("• Respect boundaries and only intervene when safety is at risk")
            Text("• Log emotional spikes and matched phrases for review")
            Text("• Use mascot mood overlays to gently reflect your child’s emotional state")
            Text("Action")
            Text("This consent can be revoked at any time. Nettie will never override your authority — she’s here to support, not replace.")
            Text("Consent currently granted")
            Text("Action")
            Button("Action") { /* Trigger Event */ }
            Text("guardian_profiles/$guardianId/consent/$childId")
            Text("granted")
            Text("timestamp")
            Text("Consent granted for $childId")
            Text("Failed to grant consent")
            Text("Missing guardian info — please sign in again")
            Text("Grant Consent")
            Text("Grant Consent")
            Button("Action") { /* Trigger Event */ }
            Text("guardian_profiles/$guardianId/consent/$childId")
            Text("granted")
            Text("timestamp")
            Text("Consent revoked for $childId")
            Text("Failed to revoke consent")
            Text("Missing guardian info — please sign in again")
            Text("Revoke Consent")
            Text("Revoke Consent")
            Spacer()
        }.padding()
        .navigationTitle("PlatformControlTab")
    }
}