import SwiftUI

struct QuestionDatabaseScreen: View {
    @StateObject private var viewModel = QuestionDatabaseViewModel()

    var body: some View {
        NavigationView {
            Text("The")
            Text("Questions")
            VStack {
            }
            VStack {
            }
            VStack {
            }
            Text("QuestionCategory")
            Text("QuestionCategory")
            Text("QuestionCategory")
            Text("QuestionCategory")
            Text("QuestionCategory")
            Text("VALUES")
            Text("Question")
            Text("values_1")
            Text("QuestionCategory")
            Text("When you imagine your ideal life, what role does family play?")
            Text("Let's explore what truly matters to you. This isn't about what you think you should want—it's about what your heart actually craves.")
            Text("QuestionType")
            Text("v1_a")
            Text("v1_b")
            Text("v1_c")
            Text("v1_d")
            Text("v1_e")
            Text("values")
            Text("Question")
            Text("values_2")
            Text("QuestionCategory")
            Text("In a relationship, what do you prioritize more?")
            Text("Here's a revealing question about what makes you feel truly secure.")
            Text("QuestionType")
            Text("v2_a")
            Text("v2_b")
            Text("v2_c")
            Text("v2_d")
            Text("v2_e")
            Text("values")
            Text("Question")
            Text("values_3")
            Text("QuestionCategory")
            Text("How do you feel about change and transformation in life?")
            Text("Some souls crave stability. Others thrive in metamorphosis. Where do you land?")
            Text("QuestionType")
            Text("v3_a")
            Text("v3_b")
            Text("v3_c")
            Text("v3_d")
            Text("v3_e")
            Text("values")
            Text("Question")
            Text("values_4")
            Text("QuestionCategory")
            Text("What drives your life decisions more?")
            Text("This reveals whether you're guided by the tangible or the intangible.")
            Text("QuestionType")
            Text("v4_a")
            Text("v4_b")
            Text("v4_c")
            Text("v4_d")
            Text("v4_e")
            Text("values")
            Text("Question")
            Text("values_5")
            Text("QuestionCategory")
            Text("How do you view traditions and established ways of doing things?")
            Text("Are you an anchor to the past or a bridge to the future?")
            Text("QuestionType")
            Text("v5_a")
            Text("v5_b")
            Text("v5_c")
            Text("v5_d")
            Text("v5_e")
            Text("values")
            Text("Question")
            Text("values_6")
            Text("QuestionCategory")
            Text("What matters more to you in making life choices?")
            Text("This reveals whether you're wired for collective harmony or individual authenticity.")
            Text("QuestionType")
            Text("v6_a")
            Text("v6_b")
            Text("v6_c")
            Text("v6_d")
            Text("v6_e")
            Text("values")
            Text("CONFLICT")
            Text("Question")
            Text("conflict_1")
            Text("QuestionCategory")
            Text("When conflict arises in a relationship, what's your natural response?")
            Text("Conflict reveals our deepest patterns. There's no right answer—only your truth.")
            Text("QuestionType")
            Text("c1_a")
            Text("c1_b")
            Text("c1_c")
            Text("c1_d")
            Text("c1_e")
            Text("conflict")
            Text("Question")
            Text("conflict_2")
            Text("QuestionCategory")
            Text("After a disagreement, how quickly do you move toward repair?")
            Text("Some hearts heal quickly. Others need time. Both are valid—but compatibility matters.")
            Text("QuestionType")
            Text("c2_a")
            Text("c2_b")
            Text("c2_c")
            Text("c2_d")
            Text("c2_e")
            Text("conflict")
            Text("Question")
            Text("conflict_3")
            Text("QuestionCategory")
            Text("How long do you remember emotional hurts from the past?")
            Text("Our emotional memory shapes how we love. Do you carry wounds or release them?")
            Text("QuestionType")
            Text("c3_a")
            Text("c3_b")
            Text("c3_c")
            Text("c3_d")
            Text("c3_e")
            Text("conflict")
            Text("Question")
            Text("conflict_4")
            Text("QuestionCategory")
            Text("How comfortable are you with direct confrontation?")
            Text("Some souls speak their truth boldly. Others protect peace through silence.")
            Text("QuestionType")
            Text("c4_a")
            Text("c4_b")
            Text("c4_c")
            Text("c4_d")
            Text("c4_e")
            Text("conflict")
            Text("Question")
            Text("conflict_5")
            Text("QuestionCategory")
            Text("The ability to say 'I'm sorry' reveals emotional maturity and humility.")
            Text("QuestionType")
            Text("c5_a")
            Text("c5_b")
            Text("c5_c")
            Text("c5_d")
            Text("c5_e")
            Text("conflict")
            Text("Question")
            Text("conflict_6")
            Text("QuestionCategory")
            Text("How do you handle personal boundaries in relationships?")
            Text("Boundaries reveal how we protect our essence while staying connected.")
            Text("QuestionType")
            Text("c6_a")
            Text("c6_b")
            Text("c6_c")
            Text("c6_d")
            Text("c6_e")
            Text("conflict")
            Text("FUTURE")
            Text("Question")
            Text("future_1")
            Text("QuestionCategory")
            Text("How do you feel about having children?")
            Text("This is one of the most important compatibility factors. Be honest with yourself.")
            Text("QuestionType")
            Text("f1_a")
            Text("f1_b")
            Text("f1_c")
            Text("f1_d")
            Text("f1_e")
            Text("f1_f")
            Text("future")
            Text("Question")
            Text("future_2")
            Text("QuestionCategory")
            Text("How important is career success and professional achievement to you?")
            Text("Some find meaning in work. Others find it elsewhere. Neither is wrong.")
            Text("QuestionType")
            Text("f2_a")
            Text("f2_b")
            Text("f2_c")
            Text("f2_d")
            Text("f2_e")
            Text("future")
            Text("Question")
            Text("future_3")
            Text("QuestionCategory")
            Text("How do you feel about relocating for love or opportunity?")
            Text("Are your roots deep in one place, or do your wings carry you anywhere?")
            Text("QuestionType")
            Text("f3_a")
            Text("f3_b")
            Text("f3_c")
            Text("f3_d")
            Text("f3_e")
            Text("future")
            Text("Question")
            Text("future_4")
            Text("QuestionCategory")
            Text("What pace of life appeals to you most?")
            Text("Do you crave the quiet or the chaos? The stillness or the storm?")
            Text("QuestionType")
            Text("f4_a")
            Text("f4_b")
            Text("f4_c")
            Text("f4_d")
            Text("f4_e")
            Text("future")
            Text("Question")
            Text("future_5")
            Text("QuestionCategory")
            Text("What are your financial goals and relationship with money?")
            Text("Money reveals values. How we earn, spend, and save tells a deeper story.")
            Text("QuestionType")
            Text("f5_a")
            Text("f5_b")
            Text("f5_c")
            Text("f5_d")
            Text("f5_e")
            Text("future")
            Text("Question")
            Text("future_6")
            Text("QuestionCategory")
            Text("Where does your mind naturally focus?")
            Text("Some live in the moment. Others build tomorrow. Where do you dwell?")
            Text("QuestionType")
            Text("f6_a")
            Text("f6_b")
            Text("f6_c")
            Text("f6_d")
            Text("f6_e")
            Text("future")
            Text("COMMUNICATION")
            Text("Question")
            Text("comm_1")
            Text("QuestionCategory")
            Text("We all speak different languages of love. What's yours?")
            Text("QuestionType")
            Text("cm1_a")
            Text("cm1_b")
            Text("cm1_c")
            Text("cm1_d")
            Text("cm1_e")
            Text("communication")
            Text("Question")
            Text("comm_2")
            Text("QuestionCategory")
            Text("How direct are you when communicating your needs?")
            Text("Do you speak plainly or paint with subtle hints?")
            Text("QuestionType")
            Text("cm2_a")
            Text("cm2_b")
            Text("cm2_c")
            Text("cm2_d")
            Text("cm2_e")
            Text("communication")
            Text("Question")
            Text("comm_3")
            Text("QuestionCategory")
            Text("How openly do you express your emotions?")
            Text("Some hearts wear their feelings on their sleeve. Others guard them carefully.")
            Text("QuestionType")
            Text("cm3_a")
            Text("cm3_b")
            Text("cm3_c")
            Text("cm3_d")
            Text("cm3_e")
            Text("communication")
            Text("Question")
            Text("comm_4")
            Text("QuestionCategory")
            Text("When someone shares a problem with you, what's your instinct?")
            Text("This reveals whether you're a fixer or a feeler.")
            Text("QuestionType")
            Text("cm4_a")
            Text("cm4_b")
            Text("cm4_c")
            Text("cm4_d")
            Text("cm4_e")
            Text("communication")
            Text("Question")
            Text("comm_5")
            Text("QuestionCategory")
            Text("How comfortable are you being vulnerable and sharing fears?")
            Text("Vulnerability is the gateway to intimacy. How easily do you open that door?")
            Text("QuestionType")
            Text("cm5_a")
            Text("cm5_b")
            Text("cm5_c")
            Text("cm5_d")
            Text("cm5_e")
            Text("communication")
            Text("Question")
            Text("comm_6")
            Text("QuestionCategory")
            Text("What role does humor play in your communication?")
            Text("Do you laugh through life or take it seriously?")
            Text("QuestionType")
            Text("cm6_a")
            Text("cm6_b")
            Text("cm6_c")
            Text("cm6_d")
            Text("cm6_e")
            Text("communication")
            Text("PHILOSOPHY")
            Text("Question")
            Text("phil_1")
            Text("QuestionCategory")
            Text("How important is spirituality or religion in your life?")
            Text("Whether you find meaning in the divine or the earthly, both paths are sacred.")
            Text("QuestionType")
            Text("p1_a")
            Text("p1_b")
            Text("p1_c")
            Text("p1_d")
            Text("p1_e")
            Text("philosophy")
            Text("Question")
            Text("phil_2")
            Text("QuestionCategory")
            Text("Are we authors of our story or characters in a written tale?")
            Text("QuestionType")
            Text("p2_a")
            Text("p2_b")
            Text("p2_c")
            Text("p2_d")
            Text("p2_e")
            Text("philosophy")
            Text("Question")
            Text("phil_3")
            Text("QuestionCategory")
            Text("How would you describe your general outlook on life?")
            Text("Do you see the glass half full, half empty, or just see the glass?")
            Text("QuestionType")
            Text("p3_a")
            Text("p3_b")
            Text("p3_c")
            Text("p3_d")
            Text("p3_e")
            Text("philosophy")
            Text("Question")
            Text("phil_4")
            Text("QuestionCategory")
            Text("Where do you find your deepest sense of meaning and purpose?")
            Text("What makes your life feel worthwhile?")
            Text("QuestionType")
            Text("p4_a")
            Text("p4_b")
            Text("p4_c")
            Text("p4_d")
            Text("p4_e")
            Text("philosophy")
            Text("Question")
            Text("phil_5")
            Text("QuestionCategory")
            Text("Do you believe people can fundamentally change?")
            Text("This belief shapes how we love—with acceptance or with hope for transformation.")
            Text("QuestionType")
            Text("p5_a")
            Text("p5_b")
            Text("p5_c")
            Text("p5_d")
            Text("p5_e")
            Text("philosophy")
            Text("Question")
            Text("phil_6")
            Text("QuestionCategory")
            Text("What's your philosophy about love itself?")
            Text("The final question. What is love to you—work or magic?")
            Text("QuestionType")
            Text("p6_a")
            Text("p6_b")
            Text("p6_c")
            Text("p6_d")
            Text("p6_e")
            Text("philosophy")
                .navigationTitle("QuestionDatabase")
        }
        .onAppear { viewModel.onEvent(QuestionDatabaseEvent.onAppear) }
    }
}
