import SwiftUI

struct QuizQuestionDatabaseScreen: View {
    @StateObject private var viewModel = QuizQuestionDatabaseViewModel()

    var body: some View {
        NavigationView {
            Text("Quiz")
            Text("These")
            Text("QuizQuestionData")
            Text("String")
            Text("String")
            Text("QuizCategory")
            Text("List")
            Text("String")
            Text("QuizOption")
            Text("String")
            Text("String")
            Text("String")
            VStack {
            }
            Text("Database")
            Text("Users")
            VStack {
            }
            VStack {
            }
            Text("EMOTIONAL")
            Text("QuizQuestionData")
            Text("quiz_1")
            Text("You've had a terrible day at work. When you get home, what do you need most?")
            Text("QuizCategory")
            Text("QuizOption")
            Text("q1_a")
            Text("Complete silence and solitude to decompress")
            Text("Needs space to process emotions alone")
            Text("QuizOption")
            Text("q1_b")
            Text("Someone to listen without trying to fix anything")
            Text("Seeks empathy and emotional validation")
            Text("QuizOption")
            Text("q1_c")
            Text("Advice and solutions to prevent it happening again")
            Text("Problem-solver who seeks practical support")
            Text("QuizOption")
            Text("q1_d")
            Text("Distraction—let's do something fun and forget about it")
            Text("Avoids dwelling on negative emotions")
            Text("This reveals how they process stress and what kind of support they need from a partner.")
            Text("QuizQuestionData")
            Text("quiz_2")
            Text("Your partner forgot your birthday. How do you react?")
            Text("QuizCategory")
            Text("QuizOption")
            Text("q2_a")
            Text("I'd be deeply hurt and need time to process the pain")
            Text("Sensitive to perceived neglect")
            Text("QuizOption")
            Text("q2_b")
            Text("Direct communicator with clear expectations")
            Text("QuizOption")
            Text("q2_c")
            Text("I'd be upset but try to understand—maybe they're stressed")
            Text("Empathetic and gives benefit of the doubt")
            Text("QuizOption")
            Text("q2_d")
            Text("Honestly, I'd probably forget too—birthdays aren't that important")
            Text("Low emphasis on traditional celebrations")
            Text("This shows how they handle disappointment and what they expect from a partner.")
            Text("QuizQuestionData")
            Text("quiz_3")
            Text("You receive unexpected wonderful news. What's your first instinct?")
            Text("QuizCategory")
            Text("QuizOption")
            Text("q3_a")
            Text("Call my partner immediately to share the excitement")
            Text("Partner is first person they turn to")
            Text("QuizOption")
            Text("q3_b")
            Text("Savor it privately for a while before telling anyone")
            Text("Processes joy internally first")
            Text("QuizOption")
            Text("q3_c")
            Text("Post about it on social media to celebrate with everyone")
            Text("Shares joy publicly and broadly")
            Text("QuizOption")
            Text("q3_d")
            Text("Stay calm—good things can change, so I don't get too excited")
            Text("Cautious optimist who guards against disappointment")
            Text("This reveals how they share joy and whether they turn to their partner first.")
            Text("VALUES")
            Text("QuizQuestionData")
            Text("quiz_4")
            Text("QuizCategory")
            Text("QuizOption")
            Text("q4_a")
            Text("Turn it in to the police immediately")
            Text("Strong moral compass, follows rules")
            Text("QuizOption")
            Text("q4_b")
            Text("Keep the cash but turn in the wallet and cards")
            Text("Pragmatic morality with some flexibility")
            Text("QuizOption")
            Text("q4_c")
            Text("Post about it on social media to find the owner")
            Text("Creative problem-solver, community-oriented")
            Text("QuizOption")
            Text("q4_d")
            Text("Practical and opportunistic")
            Text("This tests their actual ethics when no one is watching.")
            Text("QuizQuestionData")
            Text("quiz_5")
            Text("Your best friend asks you to lie to their partner for them. What do you do?")
            Text("QuizCategory")
            Text("QuizOption")
            Text("q5_a")
            Text("Absolutely not—I won't compromise my integrity")
            Text("Rigid moral boundaries")
            Text("QuizOption")
            Text("q5_b")
            Text("Refuse and tell them they need to be honest")
            Text("Values honesty and will confront friends")
            Text("QuizOption")
            Text("q5_c")
            Text("Reluctantly agree but feel terrible about it")
            Text("Loyalty sometimes overrides principles")
            Text("QuizOption")
            Text("q5_d")
            Text("Help them—loyalty to friends comes first")
            Text("Prioritizes relationships over abstract rules")
            Text("This reveals where they draw the line between loyalty and honesty.")
            Text("QuizQuestionData")
            Text("quiz_6")
            Text("You're offered a dream job that requires moving far from family. What do you do?")
            Text("QuizCategory")
            Text("QuizOption")
            Text("q6_a")
            Text("Take it without hesitation—this is my life")
            Text("Prioritizes personal growth over proximity to family")
            Text("QuizOption")
            Text("q6_b")
            Text("Take it but feel guilty about leaving family")
            Text("Ambitious but family-conscious")
            Text("QuizOption")
            Text("q6_c")
            Text("Seriously consider it but discuss with family first")
            Text("Values family input in major decisions")
            Text("QuizOption")
            Text("q6_d")
            Text("Turn it down—I can't leave my family")
            Text("Family proximity is non-negotiable")
            Text("This shows the real weight they give to family versus personal ambition.")
            Text("CONFLICT")
            Text("QuizQuestionData")
            Text("quiz_7")
            Text("During an argument, your partner says something that really hurts you. What happens next?")
            Text("QuizCategory")
            Text("QuizOption")
            Text("q7_a")
            Text("I shut down emotionally and withdraw")
            Text("Self-protective, needs space when hurt")
            Text("QuizOption")
            Text("q7_b")
            Text("I tell them immediately that they hurt me")
            Text("Direct about emotional pain")
            Text("QuizOption")
            Text("q7_c")
            Text("I say something hurtful back—it's only fair")
            Text("Reactive, seeks emotional balance")
            Text("QuizOption")
            Text("q7_d")
            Text("I try to de-escalate and address it when we're both calm")
            Text("Conflict-avoidant, strategic about timing")
            Text("This reveals their conflict style when emotions run high.")
            Text("QuizQuestionData")
            Text("quiz_8")
            Text("You and your partner have been arguing for an hour with no resolution. What do you want to do?")
            Text("QuizCategory")
            Text("QuizOption")
            Text("q8_a")
            Text("Keep talking until we resolve it—I can't rest with this unfinished")
            Text("Needs closure before moving on")
            Text("QuizOption")
            Text("q8_b")
            Text("Take a break and come back to it later with fresh perspective")
            Text("Strategic about conflict resolution")
            Text("QuizOption")
            Text("q8_c")
            Text("Agree to disagree and move on—not everything needs resolution")
            Text("Comfortable with ambiguity")
            Text("QuizOption")
            Text("q8_d")
            Text("I'm exhausted—let's just drop it")
            Text("Conflict-fatigued, may avoid resolution")
            Text("This shows their stamina for conflict and need for resolution.")
            Text("LIFE")
            Text("QuizQuestionData")
            Text("quiz_9")
            Text("It's Friday night. Your ideal evening is:")
            Text("QuizCategory")
            Text("QuizOption")
            Text("q9_a")
            Text("Quiet night at home with my partner, just us")
            Text("Values intimate one-on-one time")
            Text("QuizOption")
            Text("q9_b")
            Text("Dinner with close friends, good conversation")
            Text("Social but selective about company")
            Text("QuizOption")
            Text("q9_c")
            Text("Out at a party, concert, or social event")
            Text("Extroverted, energized by crowds")
            Text("QuizOption")
            Text("q9_d")
            Text("Alone with a book, show, or hobby—pure solitude")
            Text("Introverted, recharges alone")
            Text("This reveals their social energy and what truly recharges them.")
            Text("QuizQuestionData")
            Text("quiz_10")
            Text("You have a free Saturday with no obligations. What sounds most appealing?")
            Text("QuizCategory")
            Text("QuizOption")
            Text("q10_a")
            Text("Adventure—hiking, exploring somewhere new")
            Text("Seeks novelty and physical activity")
            Text("QuizOption")
            Text("q10_b")
            Text("Productive—tackle projects, organize, accomplish things")
            Text("Achievement-oriented even in free time")
            Text("QuizOption")
            Text("q10_c")
            Text("Relaxing—sleep in, lounge, do absolutely nothing")
            Text("Values rest and restoration")
            Text("QuizOption")
            Text("q10_d")
            Text("Creative—work on art, music, writing, or a passion project")
            Text("Driven by creative expression")
            Text("This shows what they truly value when given complete freedom.")
            Text("QuizQuestionData")
            Text("quiz_11")
            Text("Your partner wants to adopt a pet, but you're not sure. How do you decide?")
            Text("QuizCategory")
            Text("QuizOption")
            Text("q11_a")
            Text("If it makes them happy, I'm in—their joy matters most")
            Text("Partner's happiness is top priority")
            Text("QuizOption")
            Text("q11_b")
            Text("Let's discuss the practical aspects thoroughly first")
            Text("QuizOption")
            Text("q11_c")
            Text("I need time to warm up to the idea—don't rush me")
            Text("Slow to commit to big changes")
            Text("QuizOption")
            Text("q11_d")
            Text("If I'm not feeling it, the answer is no")
            Text("This reveals how they balance their needs with their partner's desires.")
            Text("INTIMACY")
            Text("QuizQuestionData")
            Text("quiz_12")
            Text("What makes you feel most loved and connected to your partner?")
            Text("QuizCategory")
            Text("QuizOption")
            Text("q12_a")
            Text("Physical affection—touch, hugs, closeness")
            Text("Physical touch is primary love language")
            Text("QuizOption")
            Text("q12_b")
            Text("Deep conversations about feelings and dreams")
            Text("Emotional intimacy through words")
            Text("QuizOption")
            Text("q12_c")
            Text("When they do thoughtful things without being asked")
            Text("Acts of service show love")
            Text("QuizOption")
            Text("q12_d")
            Text("Quality time together, undivided attention")
            Text("Presence and attention matter most")
            Text("This reveals their primary love language and intimacy needs.")
            Text("QuizQuestionData")
            Text("quiz_13")
            Text("How much alone time do you need in a relationship?")
            Text("QuizCategory")
            Text("QuizOption")
            Text("q13_a")
            Text("Very little—I want to spend most of my time with my partner")
            Text("High togetherness needs")
            Text("QuizOption")
            Text("q13_b")
            Text("Leans toward togetherness")
            Text("QuizOption")
            Text("q13_c")
            Text("A healthy balance of together time and alone time")
            Text("Balanced autonomy needs")
            Text("QuizOption")
            Text("q13_d")
            Text("Significant alone time—I need space to feel like myself")
            Text("High autonomy needs")
            Text("This shows their need for independence versus togetherness.")
            Text("QuizQuestionData")
            Text("quiz_14")
            Text("Your partner is going through a difficult time. How do you support them?")
            Text("QuizCategory")
            Text("QuizOption")
            Text("q14_a")
            Text("Give them space—they'll come to me when ready")
            Text("Respects autonomy in difficult times")
            Text("QuizOption")
            Text("q14_b")
            Toggle("Check in regularly but don't push", isOn: .constant(false))
            Text("Gentle, consistent presence")
            Text("QuizOption")
            Text("q14_c")
            Text("Stay close and encourage them to open up")
            Text("Active emotional support")
            Text("QuizOption")
            Text("q14_d")
            Text("Take action—help solve the problem causing the difficulty")
            Text("Practical support over emotional")
            Text("This reveals how they show up for a partner in crisis.")
            Text("QuizQuestionData")
            Text("quiz_15")
            Text("How do you feel about sharing passwords and having access to each other's phones?")
            Text("QuizCategory")
            Text("QuizOption")
            Text("q15_a")
            Text("Absolutely—complete transparency builds trust")
            Text("Values openness and transparency")
            Text("QuizOption")
            Text("q15_b")
            Text("I'm okay with it, though I wouldn't check without reason")
            Text("Trusts but appreciates access")
            Text("QuizOption")
            Text("q15_c")
            Text("Values privacy within trust")
            Text("QuizOption")
            Text("q15_d")
            Text("No way—everyone deserves private space")
            Text("Strong privacy boundaries")
            Text("This shows their beliefs about privacy, trust, and boundaries.")
            Text("ADDITIONAL")
            Text("QuizQuestionData")
            Text("quiz_16")
            Text("You're watching a sad movie. What's most likely to happen?")
            Text("QuizCategory")
            Text("QuizOption")
            Text("q16_a")
            Text("I cry openly—emotions are meant to be felt")
            Text("Emotionally expressive and vulnerable")
            Text("QuizOption")
            Text("q16_b")
            Text("I get teary but try to hide it")
            Text("Feels deeply but guards emotional display")
            Text("QuizOption")
            Text("q16_c")
            Text("I feel moved but don't cry")
            Text("Processes emotions internally")
            Text("QuizOption")
            Text("q16_d")
            Text("I rarely get emotional over movies")
            Text("Emotionally reserved or analytical")
            Text("This reveals their emotional expressiveness and comfort with vulnerability.")
            Text("QuizQuestionData")
            Text("quiz_17")
            Text("Someone criticizes something you're proud of. How do you react?")
            Text("QuizCategory")
            Text("QuizOption")
            Text("q17_a")
            Text("I'm crushed—it takes me days to recover")
            Text("Highly sensitive to criticism")
            Text("QuizOption")
            Text("q17_b")
            Text("I'm hurt but try to see if there's truth in it")
            Text("Sensitive but growth-oriented")
            Text("QuizOption")
            Text("q17_c")
            Text("I defend my work and explain my perspective")
            Text("Confident and assertive")
            Text("QuizOption")
            Text("q17_d")
            Text("I don't take it personally—everyone has opinions")
            Text("Thick-skinned and secure")
            Text("This shows how they handle criticism and protect their self-esteem.")
            Text("QuizQuestionData")
            Text("quiz_18")
            Text("Your partner is upset but won't tell you why. What do you do?")
            Text("QuizCategory")
            Text("QuizOption")
            Text("q18_a")
            Text("Keep asking until they open up—I need to know")
            Text("Persistent and needs resolution")
            Text("QuizOption")
            Text("q18_b")
            Text("Give them space but let them know I'm here")
            Text("Respectful of boundaries while supportive")
            Text("QuizOption")
            Text("q18_c")
            Text("Try to cheer them up and distract them")
            Text("Solution-oriented, avoids heavy emotions")
            Text("QuizOption")
            Text("q18_d")
            Text("Wait for them to come to me when ready")
            Text("Patient and non-intrusive")
            Text("This reveals how they navigate a partner's emotional withdrawal.")
            Text("ADDITIONAL")
            Text("QuizQuestionData")
            Text("quiz_19")
            Text("You witness someone being treated unfairly. What do you do?")
            Text("QuizCategory")
            Text("QuizOption")
            Text("q19_a")
            Text("Speak up immediately—I can't stay silent")
            Text("Strong sense of justice, confrontational")
            Text("QuizOption")
            Text("q19_b")
            Text("Intervene but try to de-escalate calmly")
            Text("Justice-oriented but diplomatic")
            Text("QuizOption")
            Text("q19_c")
            Toggle("Check on the person afterward privately", isOn: .constant(false))
            Text("Compassionate but conflict-avoidant")
            Text("QuizOption")
            Text("q19_d")
            Text("Stay out of it—it's not my business")
            Text("Non-confrontational, values privacy")
            Text("This tests their courage and commitment to fairness in real situations.")
            Text("QuizQuestionData")
            Text("quiz_20")
            Text("You have the chance to advance your career by taking credit for a team effort. What do you do?")
            Text("QuizCategory")
            Text("QuizOption")
            Text("q20_a")
            Text("Never—I'd make sure everyone gets recognized")
            Text("Strong integrity and team loyalty")
            Text("QuizOption")
            Text("q20_b")
            Text("I'd mention the team but highlight my contributions")
            Text("Balanced self-advocacy and fairness")
            Text("QuizOption")
            Text("q20_c")
            Text("I'd take the opportunity—that's how careers work")
            Text("Ambitious and pragmatic")
            Text("QuizOption")
            Text("q20_d")
            Text("I'd feel guilty but might do it anyway")
            Text("Conflicted between ambition and ethics")
            Text("This reveals their integrity when personal gain conflicts with fairness.")
            Text("QuizQuestionData")
            Text("quiz_21")
            Text("A close friend asks to borrow a significant amount of money. What's your response?")
            Text("QuizCategory")
            Text("QuizOption")
            Text("q21_a")
            Text("Yes, without hesitation—friends help each other")
            Text("Generous and trusting")
            Text("QuizOption")
            Text("q21_b")
            Text("Yes, but I'd want to understand the situation first")
            Text("Helpful but cautious")
            Text("QuizOption")
            Text("q21_c")
            Text("I'd offer what I can afford to lose")
            Text("Practical and protective of resources")
            Text("QuizOption")
            Text("q21_d")
            Text("No—I don't lend money to friends")
            Text("Firm boundaries around finances")
            Text("This shows how they balance generosity with financial boundaries.")
            Text("ADDITIONAL")
            Text("QuizQuestionData")
            Text("quiz_22")
            Text("You realize you were wrong in an argument. What happens next?")
            Text("QuizCategory")
            Text("QuizOption")
            Text("q22_a")
            Text("Humble and accountable")
            Text("QuizOption")
            Text("q22_b")
            Text("Accountable but needs to be understood")
            Text("QuizOption")
            Text("q22_c")
            Text("I struggle to admit it but eventually do")
            Text("QuizOption")
            Text("q22_d")
            Text("Avoids direct acknowledgment of fault")
            Text("This reveals their ability to be vulnerable and admit mistakes.")
            Text("QuizQuestionData")
            Text("quiz_23")
            Text("Your partner brings up the same issue repeatedly. How do you feel?")
            Text("QuizCategory")
            Text("QuizOption")
            Text("q23_a")
            Text("Frustrated—we already talked about this")
            Text("Values resolution and moving forward")
            Text("QuizOption")
            Text("q23_b")
            Text("Concerned—maybe I didn't really address it")
            Text("Self-reflective and empathetic")
            Text("QuizOption")
            Text("q23_c")
            Text("Annoyed but willing to discuss it again")
            Text("Patient but has limits")
            Text("QuizOption")
            Text("q23_d")
            Text("Defensive—why can't they let it go?")
            Text("Conflict-avoidant, seeks closure")
            Text("This shows their patience with unresolved emotional issues.")
            Text("QuizQuestionData")
            Text("quiz_24")
            Text("During a disagreement, your partner raises their voice. What's your reaction?")
            Text("QuizCategory")
            Text("QuizOption")
            Text("q24_a")
            Text("I shut down completely—I can't handle yelling")
            Text("Sensitive to raised voices, withdraws")
            Text("QuizOption")
            Text("q24_b")
            Text("I ask them to lower their voice calmly")
            Text("Sets boundaries while staying engaged")
            Text("QuizOption")
            Text("q24_c")
            Text("I match their energy—if they yell, I yell")
            Text("Reactive and escalates conflict")
            Text("QuizOption")
            Text("q24_d")
            Text("I stay calm—their emotions don't affect mine")
            Text("Emotionally regulated and stable")
            Text("This reveals how they handle emotional intensity in conflict.")
            Text("ADDITIONAL")
            Text("QuizQuestionData")
            Text("quiz_25")
            Text("If you could only choose one, which would you prioritize?")
            Text("QuizCategory")
            Text("QuizOption")
            Text("q25_a")
            Text("Career success and financial security")
            Text("Achievement and stability-focused")
            Text("QuizOption")
            Text("q25_b")
            Text("Deep, meaningful relationships")
            Text("Connection and intimacy-focused")
            Text("QuizOption")
            Text("q25_c")
            Text("Personal growth and self-discovery")
            Text("Self-development oriented")
            Text("QuizOption")
            Text("q25_d")
            Text("Adventure and new experiences")
            Text("Novelty and excitement-driven")
            Text("This reveals their core life priority when forced to choose.")
            Text("QuizQuestionData")
            Text("quiz_26")
            Text("How do you feel about routine and predictability in daily life?")
            Text("QuizCategory")
            Text("QuizOption")
            Text("q26_a")
            Text("I love it—routine makes me feel secure and productive")
            Text("Values structure and predictability")
            Text("QuizOption")
            Text("q26_b")
            Text("I like some routine but need variety too")
            Text("Balanced need for structure and spontaneity")
            Text("QuizOption")
            Text("q26_c")
            Text("Leans toward flexibility and change")
            Text("QuizOption")
            Text("q26_d")
            Text("I hate routine—I need constant change and excitement")
            Text("Highly spontaneous and novelty-seeking")
            Text("This shows their need for structure versus spontaneity in life.")
            Text("QuizQuestionData")
            Text("quiz_27")
            Text("Your partner wants to move to a new city for their dream job. How do you respond?")
            Text("QuizCategory")
            Text("QuizOption")
            Text("q27_a")
            Text("Let's go—I'll make it work for us")
            Text("Adaptable and partner-focused")
            Text("QuizOption")
            Text("q27_b")
            Text("Supportive but practical")
            Text("QuizOption")
            Text("q27_c")
            Text("I'd be hesitant—my life is here")
            Text("Values stability and roots")
            Text("QuizOption")
            Text("q27_d")
            Text("I'd ask them to find something local instead")
            Text("Prioritizes own stability over partner's dreams")
            Text("This reveals how they balance personal stability with supporting a partner's ambitions.")
            Text("ADDITIONAL")
            Text("QuizQuestionData")
            Text("quiz_28")
            Text("QuizCategory")
            Text("QuizOption")
            Text("q28_a")
            Text("Through words—I tell them how I feel")
            Text("Verbal affirmation as love language")
            Text("QuizOption")
            Text("q28_b")
            Text("Through actions—I do things to make their life easier")
            Text("Acts of service as love language")
            Text("QuizOption")
            Text("q28_c")
            Text("Through touch—physical affection is my way")
            Text("Physical touch as love language")
            Text("QuizOption")
            Text("q28_d")
            Text("Through gifts and thoughtful gestures")
            Text("Gift-giving as love language")
            Text("This reveals how they naturally express love and affection.")
            Text("QuizQuestionData")
            Text("quiz_29")
            Text("How important is it that your partner shares your hobbies and interests?")
            Text("QuizCategory")
            Text("QuizOption")
            Text("q29_a")
            Text("Very important—I want to share everything with them")
            Text("High need for shared activities")
            Text("QuizOption")
            Text("q29_b")
            Text("Somewhat important—some overlap is nice")
            Text("Values some shared interests")
            Text("QuizOption")
            Text("q29_c")
            Text("Not very important—differences keep things interesting")
            Text("Values independence and diversity")
            Text("QuizOption")
            Text("q29_d")
            Text("High need for individual identity")
            Text("This shows their need for shared versus separate interests in a relationship.")
            Text("QuizQuestionData")
            Text("quiz_30")
            Text("When you're feeling insecure in the relationship, what do you need?")
            Text("QuizCategory")
            Text("QuizOption")
            Text("q30_a")
            Text("Constant reassurance and affection")
            Text("High reassurance needs")
            Text("QuizOption")
            Text("q30_b")
            Text("A deep conversation about our relationship")
            Text("Needs verbal processing and clarity")
            Text("QuizOption")
            Text("q30_c")
            Text("Quality time together to reconnect")
            Text("Presence and attention restore security")
            Text("QuizOption")
            Text("q30_d")
            Text("Space to work through it on my own")
            Text("Self-soothes and processes independently")
            Text("This reveals how they seek security when feeling vulnerable in love.")
                .navigationTitle("QuizQuestionDatabase")
        }
        .onAppear { viewModel.onEvent(QuizQuestionDatabaseEvent.onAppear) }
    }
}
