import SwiftUI

struct SafeScopeVpnServiceScreen: View {
    @EnvironmentObject var container: CodexiaContainer
    
    var body: some View {
        VStack(spacing: 20) {
            Text("Momma Mobile: SafeScopeVpnService").font(.title).bold()
            Text("SafeScopeService")
            Text("nettie_prefs")
            Text("guardian_id")
            Text("child_id")
            Text("SafeScopeService")
            Text("SafeScopeService")
            Text("SafeScopeService")
            Text("SafeScopeService")
            Text("SafeScopeService")
            Text("SafeScopeService")
            Text("SafeScopeService")
            Text("SafeScopeService")
            Text("SafeScopeService")
            Text("SafeScopeService")
            Text("SafeScopeService")
            Text("SafeScopeService")
            Text("SafeScopeService")
            Text("guardianLinks/$guardianId/safeScope/$childId/enabled")
            Text("SafeScopeService")
            Text("SafeScopeService")
            Text("SafeScopeService")
            Text("SafeScopeService")
            Text("SafeScopeService")
            Text("SafeScopeService")
            Text("SafeScopeService")
            Text("SafeScopeService")
            Text("SafeScopeService")
            Text("SafeScopeService")
            Text("SafeScopeService")
            Text("SafeScopeService")
            Text("SafeScopeService")
            Text("SafeScopeService")
            Text("SafeScopeService")
            Text("example.com")
            Text(".$blocked")
            Text("SafeScopeService")
            Text("SafeScopeService")
            Spacer()
        }.padding()
        .navigationTitle("SafeScopeVpnService")
    }
}