import SwiftUI

struct ScannerGlobalsScreen: View {
    @EnvironmentObject var container: CodexiaContainer
    
    var body: some View {
        VStack(spacing: 20) {
            Text("Momma Mobile: ScannerGlobals").font(.title).bold()
            Text("ScannerGlobals")
            Text("emotion_sadness")
            Text("i want to disappear")
            Text("i feel so sad")
            Text("i am depressed")
            Text("i can't do this anymore")
            Text("emotion_anger")
            Text("i hate you")
            Text("i'm so mad")
            Text("i'm furious")
            Text("emotion_anxiety")
            Text("i'm anxious")
            Text("i'm worried")
            Text("panic attack")
            Text("threat_self_harm")
            Text("i want to hurt myself")
            Text("i want to kill myself")
            Text("self harm")
            Text("suicidal")
            Text("threat_bullying")
            Text("you're worthless")
            Text("no one likes you")
            Text("go away loser")
            Text("threat_grooming")
            Text("keep this secret")
            Text("don't tell your parents")
            Text("don't tell anyone")
            Text("don't tell your mom")
            Text("don't tell your dad")
            Text("how old are you")
            Text("what's your age")
            Text("where do you live")
            Text("what school do you go to")
            Text("are you alone")
            Text("when are your parents home")
            Text("send me pics")
            Text("show me")
            Text("meet up")
            Text("come over")
            Text("our little secret")
            Text("mature for your age")
            Text("special relationship")
            Text("talk privately")
            Text("let's talk privately")
            Text("create another account")
            Text("make another account")
            Text("get a new account")
            Text("use a different account")
            Spacer()
        }.padding()
        .navigationTitle("ScannerGlobals")
    }
}