import SwiftUI

struct TypeKtScreen: View {
    @StateObject private var viewModel = TypeKtViewModel()

    var body: some View {
        NavigationView {
            Text("Typography")
            Text("Shadow")
            Text("DrawStyle")
            Text("PlatformTextStyle")
            Text("TextStyle")
            Text("FontFamily")
            Text("FontStyle")
            Text("FontSynthesis")
            Text("FontWeight")
            Text("GenericFontFamily")
            Text("LocaleList")
            Text("BaselineShift")
            Text("LineHeightStyle")
            Text("TextDecoration")
            Text("TextGeometricTransform")
            Text("TextIndent")
            Text("TextMotion")
            Text("TextUnitKt")
            Text("Metadata")
            Text("DefaultConstructorMarker")
            Text("JADX")
            Text("JADX")
            Text("\\u0000\\n\\n\\u0000\\n\\u0002\\u0018\\u0002\\n\\u0002\\b\\u0003")
            VStack {
            }
            Text("Typography")
            Text("GenericFontFamily")
            Text("FontWeight")
            Text("GenericFontFamily")
            Text("TextStyle")
            Text("GenericFontFamily")
            Text("FontWeight")
            Text("GenericFontFamily")
            Text("TextStyle")
            Text("GenericFontFamily")
            Text("FontWeight")
            Text("GenericFontFamily")
            Text("TextStyle")
            Text("GenericFontFamily")
            Text("FontWeight")
            Text("GenericFontFamily")
            Text("TextStyle")
            Text("GenericFontFamily")
            Text("FontWeight")
            Text("GenericFontFamily")
            Text("TextStyle")
            Text("GenericFontFamily")
            Text("FontWeight")
            Text("GenericFontFamily")
            Text("TextStyle")
            Text("GenericFontFamily")
            Text("FontWeight")
            Text("GenericFontFamily")
            Text("TextStyle")
            Text("GenericFontFamily")
            Text("FontWeight")
            Text("GenericFontFamily")
            Text("TextStyle")
            Text("GenericFontFamily")
            Text("FontWeight")
            Text("GenericFontFamily")
            Text("TextStyle")
            Text("GenericFontFamily")
            Text("FontWeight")
            Text("GenericFontFamily")
            Text("TextStyle")
            Text("GenericFontFamily")
            Text("FontWeight")
            Text("GenericFontFamily")
            Text("TextStyle")
            Text("GenericFontFamily")
            Text("FontWeight")
            Text("GenericFontFamily")
            Text("TextStyle")
            Text("GenericFontFamily")
            Text("FontWeight")
            Text("GenericFontFamily")
            Text("TextStyle")
            Text("GenericFontFamily")
            Text("FontWeight")
            Text("GenericFontFamily")
            Text("TextStyle")
            Text("GenericFontFamily")
            Text("FontWeight")
            Text("GenericFontFamily")
            Text("Typography")
            VStack {
            }
            Text("Typography")
                .navigationTitle("TypeKt")
        }
        .onAppear { viewModel.onEvent(TypeKtEvent.onAppear) }
    }
}
