import SwiftUI

struct TypeScreen: View {
    @StateObject private var viewModel = TypeViewModel()

    var body: some View {
        NavigationView {
            Text("Typography")
            Text("TextStyle")
            Text("FontFamily")
            Text("FontWeight")
            Button(action: { }) {
                Text("SoulLink")
            }
            Text("Typography")
            Text("Display")
            Text("TextStyle")
            Text("FontFamily")
            Text("FontWeight")
            Text("TextStyle")
            Text("FontFamily")
            Text("FontWeight")
            Text("TextStyle")
            Text("FontFamily")
            Text("FontWeight")
            Text("Headlines")
            Text("TextStyle")
            Text("FontFamily")
            Text("FontWeight")
            Text("TextStyle")
            Text("FontFamily")
            Text("FontWeight")
            Text("TextStyle")
            Text("FontFamily")
            Text("FontWeight")
            Text("Titles")
            Text("TextStyle")
            Text("FontFamily")
            Text("FontWeight")
            Text("TextStyle")
            Text("FontFamily")
            Text("FontWeight")
            Text("TextStyle")
            Text("FontFamily")
            Text("FontWeight")
            Text("Body")
            Text("TextStyle")
            Text("FontFamily")
            Text("FontWeight")
            Text("TextStyle")
            Text("FontFamily")
            Text("FontWeight")
            Text("TextStyle")
            Text("FontFamily")
            Text("FontWeight")
            Text("Labels")
            Text("TextStyle")
            Text("FontFamily")
            Text("FontWeight")
            Text("TextStyle")
            Text("FontFamily")
            Text("FontWeight")
            Text("TextStyle")
            Text("FontFamily")
            Text("FontWeight")
                .navigationTitle("Type")
        }
        .onAppear { viewModel.onEvent(TypeEvent.onAppear) }
    }
}
