import SwiftUI

struct UserScreen: View {
    @StateObject private var viewModel = UserViewModel()

    var body: some View {
        NavigationView {
            Text("Timestamp")
            Text("DocumentId")
            Text("ServerTimestamp")
            Text("User")
            Text("DocumentId")
            Text("String")
            Text("String")
            Text("String")
            Text("Int")
            Text("Gender")
            Text("Orientation")
            Text("Location")
            Text("String")
            Text("List")
            Text("String")
            Text("Photo")
            Text("PhotoModerationStatus")
            Text("List")
            Text("Boolean")
            Text("Matching")
            Text("Gender")
            Text("Int")
            Text("Int")
            Text("Int")
            Text("Profile")
            Text("Boolean")
            Text("Boolean")
            Text("Boolean")
            Text("Legal")
            Text("Boolean")
            Text("Boolean")
            Text("Timestamp")
            Text("Candidate")
            Text("List")
            Text("Boolean")
            Text("Push")
            Text("String")
            Text("Questionnaire")
            Text("Int")
            Text("Map")
            Text("Match")
            Text("MatchState")
            Text("String")
            Text("Boolean")
            Text("Boolean")
            Text("Second")
            Text("Boolean")
            Text("Int")
            Text("Timestamp")
            Text("Timestamp")
            Text("Authenticity")
            Text("Double")
            Text("Boolean")
            Text("ServerTimestamp")
            Text("Timestamp")
            Text("ServerTimestamp")
            Text("Timestamp")
            Text("Location")
            Text("Double")
            Text("Double")
            Text("String")
            Text("String")
            Text("String")
            VStack {
            }
            Text("MALE")
            Text("FEMALE")
            VStack {
            }
            Text("STRAIGHT")
            Text("GAY")
            Text("LESBIAN")
            Text("BISEXUAL")
            Text("PANSEXUAL")
            Text("ASEXUAL")
            Text("OTHER")
            VStack {
            }
            Text("SEARCHING")
            Text("Waiting")
            Text("Waiting")
            Text("MATCHED")
            Text("DECLINED")
            Text("GHOSTED")
            VStack {
            }
            Text("PENDING")
            Text("APPROVED")
            Text("REJECTED")
            Text("FLAGGED")
                .navigationTitle("User")
        }
        .onAppear { viewModel.onEvent(UserEvent.onAppear) }
    }
}
